export default class CreditScreen extends Phaser.Scene {
    
    public content: string[] = [
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "MOONSHOT presents",
        "",
        "a RA8BITS production",
        "",
        "HOPPA!",
        "",
        "Lead Cast",
        "Male Ra8bit",
        "",
        "Supporting Cast",
        "Female Ra8bit",
        "",
        "Casting Director",
        "DandyBanger",
        "",
        "Music Composer",
        "Loony chitptoon",
        "Public Domain",
        "jsfxr",
        "",
        "Costume Designer",
        "Miley Cyrus",
        "",
        "Associate Producers",
        "Juan Concreto",
        "",
        "Editors",
        "The Lost Ra8bits",
        "",
        "Production Designer",
        "Ninkwondo",
        "",
        "Director of Photography",
        "DandyBanger",
        "",
        "Executive Producer",
        "Crypt0 King",
        "",
        "Writers",
        "c0ntrol zero",
        "Pixel8bit",
        "DandyBanger",
        "",
        "Director",
        "CZ",
        "",
        "Game Designer",
        "c0ntrol zero",
        "Pixel8bit",
        "DandyBanger",
        "",
        "Sound engineer",
        "Retro OpenGame Art",
        "FreeSound",
        "",
        "Musical Composition",
        "Nicole Marie T",
        "BGM The Slimeking's Tower",
        "DeltaBreaker",
        "Bottomless Pit Man",
        "@wyver9",
        "Snabisch http://audiojungle.net/user/Snabisch",
        "Mega Pixel Music Lab",
        "Christovix",
        "Kim Lightyear",
        "3xBlast",
        "Trevor Lentz",
        "(SubspaceAudio) Juhani Junkala",
        "Tad Miller",
        "",
        "",
        "Special thanks to",
        "Vitalik",
        "Shef",
        "Crypt0 King",
        "x22",
        "Luis",
        "Winnie",
        "Joshua",
        "Borris Stain",
        "Shubham",
        "Rony",
        "Rohan",
        "Jill",
        "Akhi1",
        "Genesis",
        "Elon",
        "Crypto Dasha",
        "Crypto Baby",
        "Juli Cold",
        "Niki",
        "Claire",
        "Joy",
        "Chad",
        "Amber",
        "Yeqi",
        "Ms Krasota",
        "CryptoSeas",
        "Pure Evil",
        "Smack",
        "Rick",
        "Crypto Hunter",
        "David",
        "Pratik",
        "Joonas",
        "Furkan",
        "Light",
        "Jackson",
        "Joe",
        "K",
        "Akhi1",
        "Hussam",
        "Anastasia",
        "",
        "$MSHOT",
        "",

    ];

    constructor(name: string)  {
        super(name);
    }

   
}